name: Py Lambda Deploy From Subdirectory
author: Evan Schechter
description: Deploy python code to AWS Lambda from any directory within your repo with dependencies in a separate layer.
inputs:
  lambda_function_name:
    description: The Lambda function name. Check the AWS docs/readme for examples.
    required: true
  subdirectory:
    description: A relative path to the subdirectory containing the lambda function and dependencies to deploy.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subdirectory }}
    - ${{ inputs.lambda_function_name }}
branding:
  icon: 'layers'
  color: 'yellow'
